# Period
mode : 'prediction'

# Params
params :  {
            'objective'        : 'regression', 
            'metric'           : 'mae',
            'lambda_l1'        :  3.169673e-03,
            'lambda_l2'        : 2.801700e-08,
            'num_leaves'       : 223,
            'learning_rate'    : 1.067114e-03,
            'max_depth'        : 5,
            'min_child_samples': 44,
            'force_col_wise'   : True,
            'num_iterations'   : 300,
        #     'early_stopping_round':100,
        #     'boosting' : boosting_type,
        #     'feature_fraction': trial.suggest_uniform('feature_fraction', 0.1, 0.4),
        #     #'bagging_fraction': trial.suggest_uniform('bagging_fraction', 0.4, 1.0),
        #     #'bagging_freq': trial.suggest_int('bagging_freq', 1, 30),
        }